{{- if .Values.minikube.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "app.name" . }}.test
      http:
        paths:
          - path: {{ .Values.minikube.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.name" . }}-service
                port:
                  number: 80
{{- end }}