apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: client
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "app.name" . }}
  sessionAffinity: None
  type: ClusterIP
